<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="observer/**/*.cs" />
    <Compile Remove="worker/**/*.cs" />
    <ProjectReference Include="../../core/Merkle.Core.csproj" />
  </ItemGroup>
</Project>
